Use boost::shared_ptr instead of yae::shared_ptr
... due to build failure which I have no time to fix right now:
[  1%] Building CXX object CMakeFiles/aeyae.dir/yae/utils/yae_plugin_registry.cpp.o
/opt/local/include/boost/atomic/detail/ops_gcc_ppc.hpp: In member function 'size_t yae::ref_count_base::increment_shared()':
/opt/local/include/boost/atomic/detail/ops_gcc_ppc.hpp:231: error: impossible constraint in 'asm'